name: daf_plus_plus
description: Keep track of your Daf Yomi learning with the only English Daf Yomi tracker!
version: 0.5.1+8

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  google_sign_in: ^4.5.1
  firebase_auth: ^0.15.4
  firebase_crashlytics: ^0.1.3+3
  firebase_performance: ^0.3.1+8
  cloud_firestore: 0.13.4
  mobx: ^1.2.1+1
  intl: ^0.16.1
  flutter_mobx: ^1.1.0+1
  fluttertoast: ^4.0.0
  google_fonts: ^0.3.9
  scrollable_positioned_list: ^0.1.7
  flutter_sticky_header: 0.4.1
  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^1.4.4+4
  url_launcher: ^5.4.2
  provider: ^4.0.4
  dynamic_theme: ^1.0.1
  kosher_dart: ^2.0.1
  package_info: ^0.4.0+18

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0
  
dependency_overrides:
  path: 1.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/he.json
    - assets/icon/daf-white-on-transperant.png
    - assets/icon/pp-white-on-transperant.png
    - assets/fonts/
