name: CI/CD
on: [pull_request, push]

jobs:

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.0-12.3.pre'
        channel: 'beta'
    - run: flutter config --enable-web
    - run: flutter pub get
    - name: Build
      run: |
        mkdir $HOME/secrets
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        --output $HOME/secrets/secrets.tar secrets.tar.gpg
        tar xvf $HOME/secrets/secrets.tar
        flutter build appbundle
        flutter build apk
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/bundle/release
    # - name: Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "build/app/outputs/apk/release/app-release.apk"
    #     token: ${{ secrets.TOKEN }}

    - name: Release Android Testers
      if: (github.base_ref == 'test' && github.event_name == 'pull_request')
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        release_notes: "a new version"
        file: build/app/outputs/apk/release/app-release.apk

    - name: Build Web
      if: (github.base_ref == 'test-web' && github.event_name == 'pull_request')
      run: |
        flutter build web --release
        cp -R build/web/* public/
    - name: Release Web
      if: (github.base_ref == 'test-web' && github.event_name == 'pull_request')
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
